// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetShop.Data.Context;

#nullable disable

namespace PetShop.Data.Migrations;

[DbContext(typeof(PetShopDbContext))]
partial class PetShopDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.6")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("PetShop.Domain.Entities.Category", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<DateTime>("CreatedUtc").ValueGeneratedOnAdd().HasColumnType("datetime2").HasDefaultValueSql("SYSUTCDATETIME()");
            b.Property<string>("Description").HasMaxLength(500).HasColumnType("nvarchar(500)");
            b.Property<string>("Metadata").HasColumnType("nvarchar(max)");
            b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.HasKey("Id");
            b.HasIndex("Name").IsUnique();
            b.ToTable("Categories");
        });

        modelBuilder.Entity("PetShop.Domain.Entities.Pet", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<int>("AgeMonths").HasColumnType("int");
            b.Property<string>("Breed").HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<int>("CategoryId").HasColumnType("int");
            b.Property<DateTime>("CreatedUtc").ValueGeneratedOnAdd().HasColumnType("datetime2").HasDefaultValueSql("SYSUTCDATETIME()");
            b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<string>("OwnerEmail").HasMaxLength(256).HasColumnType("nvarchar(256)");
            b.Property<decimal>("Price").HasColumnType("decimal(18,2)");
            b.Property<int>("Status").HasColumnType("int");
            b.Property<DateTime?>("UpdatedUtc").HasColumnType("datetime2");
            b.HasKey("Id");
            b.HasIndex("CategoryId");
            b.HasIndex("OwnerEmail");
            b.HasIndex("Status");
            b.ToTable("Pets");
        });

        modelBuilder.Entity("PetShop.Domain.Entities.Plant", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<DateTime>("CreatedUtc").ValueGeneratedOnAdd().HasColumnType("datetime2").HasDefaultValueSql("SYSUTCDATETIME()");
            b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<decimal>("Price").HasColumnType("decimal(18,2)");
            b.Property<string>("Species").HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<DateTime?>("UpdatedUtc").HasColumnType("datetime2");
            b.HasKey("Id");
            b.ToTable("Plants");
        });

        modelBuilder.Entity("PetShop.Domain.Entities.UsesGroup", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<DateTime>("CreatedUtc").ValueGeneratedOnAdd().HasColumnType("datetime2").HasDefaultValueSql("SYSUTCDATETIME()");
            b.Property<string>("Description").HasMaxLength(500).HasColumnType("nvarchar(500)");
            b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<int>("SubjectId").HasColumnType("int");
            b.Property<int>("Type").HasColumnType("int");
            b.HasKey("Id");
            b.HasIndex("Type", "SubjectId");
            b.ToTable("UsesGroups");
        });

        modelBuilder.Entity("PetShop.Data.StoredProcedures.PetSearchResult", b =>
        {
            b.Property<int>("Id").HasColumnType("int");
            b.Property<string>("Breed").HasColumnType("nvarchar(max)");
            b.Property<string>("CategoryName").IsRequired().HasColumnType("nvarchar(max)");
            b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");
            b.Property<decimal>("Price").HasColumnType("decimal(18,2)");
            b.Property<int>("Status").HasColumnType("int");
            b.HasNoKey();
            b.ToTable((string)null);
        });

        modelBuilder.Entity("PetShop.Data.StoredProcedures.PlantAddResult", b =>
        {
            b.Property<int>("Id").HasColumnType("int");
            b.Property<DateTime>("CreatedUtc").HasColumnType("datetime2");
            b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");
            b.Property<decimal>("Price").HasColumnType("decimal(18,2)");
            b.Property<string>("Species").HasColumnType("nvarchar(max)");
            b.HasNoKey();
            b.ToTable((string)null);
        });

        modelBuilder.Entity("PetShop.Domain.Entities.Pet", b =>
        {
            b.HasOne("PetShop.Domain.Entities.Category", "Category")
                .WithMany("Pets").HasForeignKey("CategoryId")
                .OnDelete(DeleteBehavior.Restrict).IsRequired();
            b.Navigation("Category");
        });

        modelBuilder.Entity("PetShop.Domain.Entities.Category", b => b.Navigation("Pets"));
    }
}
